CREATE DATABASE [projeto-evolucional]
GO
USE [master]
GO
CREATE LOGIN [projeto-evolucional-usr] WITH PASSWORD='6s@f30@54J$gl2M', DEFAULT_DATABASE=[projeto-evolucional], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [projeto-evolucional]
GO
CREATE USER [projeto-evolucional-usr] FOR LOGIN [projeto-evolucional-usr] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember 'db_datareader', 'projeto-evolucional-usr'
GO
EXEC sp_addrolemember 'db_datawriter', 'projeto-evolucional-usr'
GO
EXEC sp_addrolemember 'db_owner', 'projeto-evolucional-usr'
GO
CREATE TABLE DBO.[USUARIOS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[LOGIN] VARCHAR(30) NOT NULL,
	[PASS] VARCHAR(50) NOT NULL,	
	[DATA] DATETIME NOT NULL DEFAULT ((GETDATE()))
)
GO
CREATE TABLE DBO.[ALUNOS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[NOME] VARCHAR(400) NOT NULL,
	[DATA] DATETIME NOT NULL DEFAULT ((GETDATE()))
)
GO
CREATE UNIQUE INDEX IX_UK_ALUNO_NOME ON DBO.[ALUNOS]([NOME])
GO 
CREATE TABLE DBO.[DISCIPLINAS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[NOME] VARCHAR(255) NOT NULL,
	[DATA] DATETIME NOT NULL DEFAULT ((GETDATE()))
)
GO
CREATE TABLE DBO.[MATRICULAS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[ALUNO_ID] INT NOT NULL,
	[DISCIPLINA_ID] INT NOT NULL,	
	[DATA] DATETIME NOT NULL DEFAULT ((GETDATE()))
)
GO
ALTER TABLE DBO.[MATRICULAS] ADD FOREIGN KEY ([ALUNO_ID]) REFERENCES [ALUNOS]([ID])
GO
ALTER TABLE DBO.[MATRICULAS] ADD FOREIGN KEY ([DISCIPLINA_ID]) REFERENCES [DISCIPLINAS]([ID])
GO
CREATE TABLE DBO.[NOTAS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[MATRICULA_ID] INT NOT NULL,
	[NOTA] NUMERIC(4,2) NULL,
	[DATA] DATETIME NOT NULL DEFAULT ((GETDATE()))
)
GO
ALTER TABLE DBO.[NOTAS] ADD FOREIGN KEY ([MATRICULA_ID]) REFERENCES [MATRICULAS]([ID])
GO
IF (NOT EXISTS (SELECT * FROM DBO.[USUARIOS] WITH (NOLOCK) WHERE [LOGIN] = ''))
BEGIN
	INSERT INTO DBO.[USUARIOS] ([LOGIN], [PASS]) VALUES ('candidato-evolucional', '3d395a27ffda77a5af6b4cfa8c1c6ec9')
END
GO
CREATE NONCLUSTERED INDEX [IX_MATRICULA_ALUNO] ON [dbo].[MATRICULAS] ([DISCIPLINA_ID]) INCLUDE ([ID],[ALUNO_ID])
GO
CREATE NONCLUSTERED INDEX [IX_NOTAS_MATRICULA] ON [dbo].[NOTAS] ([MATRICULA_ID]) INCLUDE ([ID],[NOTA])
GO